Repository flagbit/akeneo-reference-entity-table-bundle, pull requests merged in 2020-09, with the labels that each got.

#6 Fix package name for composer require
  README.md
Labels: bug, documentation

#7 Fix of empty labels editing in localized select
  src/Resources/public/reference-entity/attribute/table/type/localized-select.tsx
Labels: bug, size/XS

#8 Introduce JS Code Analysis tool
  .github/workflows/main.yml
  .gitignore
  .prettierrc.json
  package.json
  src/Resources/public/reference-entity/attribute/table/modal.tsx
  src/Resources/public/reference-entity/attribute/table/reducer.ts
  src/Resources/public/reference-entity/attribute/table/row.tsx
  src/Resources/public/reference-entity/attribute/table/table.ts
  src/Resources/public/reference-entity/attribute/table/type/localized-select.tsx
  src/Resources/public/reference-entity/attribute/table/type/number.tsx
  src/Resources/public/reference-entity/attribute/table/type/select.tsx
  src/Resources/public/reference-entity/attribute/table/type/text.tsx
  src/Resources/public/reference-entity/attribute/table/type/type.ts
  src/Resources/public/reference-entity/attribute/table/view.tsx
  src/Resources/public/reference-entity/record/table/cell.tsx
  src/Resources/public/reference-entity/record/table/table.tsx
  src/Resources/public/reference-entity/record/table/type/localized-select.tsx
  src/Resources/public/reference-entity/record/table/type/number.tsx
  src/Resources/public/reference-entity/record/table/type/select.tsx
  src/Resources/public/reference-entity/record/table/type/text.tsx
  src/Resources/public/reference-entity/record/table/type/type.ts
  src/Resources/public/reference-entity/record/table/view.tsx
  tsconfig.json
  tslint.json
  yarn.lock
Labels: enhancement

#10 Move akeneo repository path to github secrets
  .github/workflows/main.yml
Labels: size/XS
